# Generated by Django 2.2 on 2020-05-12 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_name', models.CharField(max_length=64, verbose_name='接口名称')),
                ('api_test_desc', models.CharField(max_length=100, null=True, verbose_name='接口描述')),
                ('api_test_user', models.CharField(max_length=64, verbose_name='测试人员')),
                ('api_test_url', models.CharField(max_length=100, verbose_name='url地址')),
                ('api_test_value', models.CharField(max_length=200, verbose_name='请求参数')),
                ('api_test_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=16, null=True, verbose_name='请求方法')),
                ('api_test_result', models.CharField(max_length=100, null=True, verbose_name='测试结果')),
                ('api_test_bug', models.CharField(choices=[('null', ' '), ('是', '是'), ('否', '否')], default='null', max_length=4, verbose_name='是否有Bug')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_api_test', to='product.Product')),
            ],
            options={
                'verbose_name': '接口测试',
                'verbose_name_plural': '接口测试',
            },
        ),
    ]
