# Generated by Django 2.2 on 2020-05-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20200512_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_test',
            name='api_test_method',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post')], default='get', max_length=16, null=True, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='api_test',
            name='api_test_value',
            field=models.TextField(default='{ }', verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='api_test',
            name='header',
            field=models.TextField(default='{ }', verbose_name='请求头'),
        ),
    ]
