# Generated by Django 2.2 on 2020-05-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_auto_20200512_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_test',
            name='web_test_result1',
            field=models.TextField(blank=True, default=' ', verbose_name='预期测试结果'),
        ),
    ]
