# Generated by Django 2.2 on 2020-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('product_desc', models.CharField(max_length=200, verbose_name='项目描述')),
                ('producter', models.CharField(max_length=200, verbose_name='项目负责人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '项目管理',
            },
        ),
    ]
