# Generated by Django 2.2 on 2020-05-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_test',
            name='web_test_input',
            field=models.CharField(max_length=100, null=True, verbose_name='输入值'),
        ),
        migrations.AlterField(
            model_name='web_test',
            name='web_test_plural',
            field=models.CharField(choices=[('singular', 'singular'), ('plural', 'plural')], default='singular', max_length=20, verbose_name='单数或复数'),
        ),
        migrations.AlterField(
            model_name='web_test',
            name='web_test_result',
            field=models.TextField(default=' ', verbose_name='预期测试结果'),
        ),
        migrations.AlterField(
            model_name='web_test',
            name='web_test_result_finaly',
            field=models.TextField(default=' ', verbose_name='最终测试结果'),
        ),
    ]
